
# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "dist/**/*.{html,php,htm}"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*
    - .gallery
    - .gallery a
    - .mfp-bg
    - .mfp-wrap
    - .mfp-container
    - .mfp-container
    - .mfp-wrap
    - .mfp-zoom-in.mfp-wrap.mfp-ready .mfp-content
    - .mfp-zoom-in.mfp-wrap .mfp-content
    - .mfp-auto-cursor .mfp-content
    - .mfp-inline-holder .mfp-content
    - .mfp-ajax-holder .mfp-content
    - .mfp-s-ready .mfp-preloader
    - .mfp-preloader
    - .mfp-zoom-in.mfp-bg.mfp-ready
    - .mfp-zoom-in.mfp-bg
    - .mfp-bg
    - .mfp-container:before
    - .mfp-hide
    - .button.mfp-close
    - .button.mfp-arrow
    - .mfp-close
    - .mfp-close-btn-in .mfp-close
    - .mfp-close:hover
    - .mfp-close:focus
    - .mfp-content
    - .mfp-close
    - .mfp-arrow
    - .mfp-image-holder
    - .mfp-counter
    - .mfp-arrow-left
    - .mfp-arrow-right
    - img.mfp-img
    - .mfp-figure
    - .mfp-figure figure
    - .mfp-bottom-bar
    - .mfp-title
    - .mfp-counter
    - .mfp-zoom-out-cur
    - .mfp-zoom-out-cur .mfp-image-holder .mfp-close
    - .mfp-image-holder .mfp-close
    - .mfp-iframe-holder .mfp-close
    - .mfp-close-btn-in .mfp-close
    - .mfp-close:focus
    - .mfp-close:hover
    - button.mfp-arrow
    - button.mfp-close
    - .sticky.is-at-top.is-stuck
    - .sticky.is-stuck
    - .sticky

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "assets/.htaccess" # <- specify import invisible file .htaccess
    - "assets/**" # <- import all files inside assets/
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/motion-ui/src"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Libraries requried by Foundation
    # - "bower_components/jquery/dist/jquery.js" # <- alternatively utilize Google jQuery CDN
    - "bower_components/what-input/dist/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
    # - "bower_components/foundation-sites/js/foundation.util.mediaQuery.js"
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    # - "bower_components/foundation-sites/js/foundation.abide.js"
    # - "bower_components/foundation-sites/js/foundation.accordion.js"
    # - "bower_components/foundation-sites/js/foundation.accordionMenu.js"
    # - "bower_components/foundation-sites/js/foundation.drilldown.js"
    # - "bower_components/foundation-sites/js/foundation.dropdown.js"
    # - "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
    - "bower_components/foundation-sites/js/foundation.equalizer.js"
    # - "bower_components/foundation-sites/js/foundation.interchange.js"
    - "bower_components/foundation-sites/js/foundation.magellan.js"
    # - "bower_components/foundation-sites/js/foundation.offcanvas.js"
    # - "bower_components/foundation-sites/js/foundation.orbit.js"
    - "bower_components/foundation-sites/js/foundation.responsiveMenu.js"
    - "bower_components/foundation-sites/js/foundation.responsiveToggle.js"
    # - "bower_components/foundation-sites/js/foundation.reveal.js"
    # - "bower_components/foundation-sites/js/foundation.slider.js"
    - "bower_components/foundation-sites/js/foundation.sticky.js"
    # - "bower_components/foundation-sites/js/foundation.tabs.js"
    # - "bower_components/foundation-sites/js/foundation.toggler.js"
    # - "bower_components/foundation-sites/js/foundation.tooltip.js"
    # - "bower_components/foundation-sites/js/foundation.zf.responsiveAccordionTabs.js"
    - "js/app-min.js"
